### ISSUE TITLE
Support keycloak 22.0.1

### ISSUE THREAD

**Issue by s1341** [justin-stephenson/scim-keycloak-user-storage-spi#11]
It seems that this breaks when used with keycloak 22.0.1. Do we need to build against the updated keycloak?

**Comment by justin-stephenson** [comment]
Hi, I recently filed https://github.com/keycloak/keycloak/issues/22087

I couldn't find any workaround, I have been able to use keycloak-20.0.5 for the time being.

**Comment by justin-stephenson** [comment]
Hello @s1341 I created https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/pull/12 to update to Keycloak 21.1.2. 

I will submit a new PR to update to 22.X at a later point, it has some changes requiring a quite new version of java.

**Comment by s1341** [comment]
Ok. Please let me know when you make that PR. I am meanwhile on 20.0.3.

**Comment by justin-stephenson** [comment]
@s1341 are you okay to close this issue?

**Comment by s1341** [comment]
yup.
